include: [".well-known"]

# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://mauaccounts.net'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: MAU Accounts DAO
# Description of the Site
description: Mutual obligations accounting system
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: MAU, USDMAU, obligations, mutual, tokens, provider
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 # hero
#heroimage: https://images.pexels.com/photos/3184430/pexels-photo-3184430.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 # four hands
#heroimage: https://images.pexels.com/photos/7988207/pexels-photo-7988207.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 # office
#heroimage: https://images.pexels.com/photos/8278915/pexels-photo-8278915.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 # asian
#heroimage: https://images.pexels.com/photos/3183148/pexels-photo-3183148.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # devices on table
#heroimage: https://images.pexels.com/photos/8101928/pexels-photo-8101928.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940 # asian team in office
#heroimage: https://images.pexels.com/photos/12901016/pexels-photo-12901016.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # palace
#heroimage: https://images.pexels.com/photos/3184423/pexels-photo-3184423.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # many hands
#heroimage: https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # man and woman
heroimage: https://images.pexels.com/photos/3785935/pexels-photo-3785935.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # gears
#heroimage: https://images.pexels.com/photos/3182787/pexels-photo-3182787.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # team in loft
#heroimage: https://images.pexels.com/photos/3182774/pexels-photo-3182774.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # team on table
#heroimage: https://images.pexels.com/photos/3182763/pexels-photo-3182763.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # room in loft
#heroimage: https://images.pexels.com/photos/3182832/pexels-photo-3182832.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # white man
#heroimage: https://images.pexels.com/photos/2962231/pexels-photo-2962231.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # team
#heroimage: https://images.pexels.com/photos/3182762/pexels-photo-3182762.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # white man in loft
#heroimage: https://images.pexels.com/photos/8127702/pexels-photo-8127702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # people in white room
#heroimage: https://images.pexels.com/photos/3182789/pexels-photo-3182789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # white man teaches
#heroimage: https://images.pexels.com/photos/6340698/pexels-photo-6340698.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # mutual hands
#heroimage: https://images.pexels.com/photos/9242834/pexels-photo-9242834.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # childs and robots
#heroimage: https://images.pexels.com/photos/8386422/pexels-photo-8386422.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # hands human robot wb
#heroimage: https://images.pexels.com/photos/8386434/pexels-photo-8386434.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # hands human robot color
#heroimage: https://images.pexels.com/photos/8438918/pexels-photo-8438918.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # chess human robot
#heroimage: https://images.pexels.com/photos/8294753/pexels-photo-8294753.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2 # robot with man bedroom

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: admin@mauaccounts.com
telegram_username: 'mau_accounts'
telegram_bot_username: 'mau_accounts_bot'
twitter_username:
instagram_username:
linkedin_username:
#github_username: mau-accounts-dao
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
scopuly_ticker: 'USDMAU-XLM/GABL7PXSAV4W4L32PI6E46HLLSMTEUKRDUMAY2Q6JXITNV2QCWABRAOB/native'

# Google Analytics
google-analytics: G-JFCDPG42Y2

# Disqus
disqus-shortname:

# Name of the Author
author-name: MAU Accounts DAO
# URL for the Image of the Author
#author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-image: https://mauaccounts.net/assets/images/mau-logo.png
# 60 Words About the Author
author-about: MAU Accounts DAO is an Autonomous Decentralized Organization that provides services for organizing a system of accounting for non-financial mutual obligations of members of local communities. We are a fellowship and a collective of People and a commonwealth of Robots. And, of course, Cats too ;)
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://mauaccounts.net
# footer
author-short: Mutual obligations accounting system of Future

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "news/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
